name: Question
description: Ask a question about usage or setup
labels: ["question"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      options:
        - Grok Dataset Builder (Chrome Extension)
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
    validations:
      required: true
